apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - networkpolicies.yaml
  - helmrepository.yaml
  - ../../../secrets/prod/arc-github-app.enc.yaml
  - rbac-secret-access.yaml
  - controller-helmrelease.yaml
  - runner-scale-set-helmrelease.yaml
