apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system-namespace.yaml
  - flux-instance.yaml
  - ../../../infrastructure/controllers/cluster-baseline
  - operator-kustomization.yaml
  - infra-kustomization.yaml
  - upgrades-kustomization.yaml
