apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  interval: 1h
  releaseName: flux-operator
  chart:
    spec:
      chart: flux-operator
      version: 0.46.x
      sourceRef:
        kind: HelmRepository
        name: flux-operator
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 512Mi
