apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../infrastructure/runners/actions-runner-controller
  - ../../../infrastructure/upgrade/tuppr
  - workloads-kustomization.yaml
