apiVersion: tuppr.home-operations.com/v1alpha1
kind: KubernetesUpgrade
metadata:
  name: kubernetes
  namespace: system-upgrade
spec:
  kubernetes:
    # renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
    version: v1.35.3
  healthChecks:
    - apiVersion: v1
      kind: Node
      expr: status.conditions.filter(c, c.type == 'Ready').all(c, c.status == 'True')
      timeout: 10m
  maintenance:
    windows:
      - start: 30 2 * * 0
        duration: 4h
        timezone: UTC
